apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"tekton.dev/pipelines.minVersion":"0.17.0","tekton.dev/tags":"build-tool"},"labels":{"app.kubernetes.io/version":"0.1"},"name":"npm","namespace":"tom-pipeline-from-scratch"},"spec":{"description":"This task can be used to run npm goals on a project.\nThis task can be used to run npm goals on a project where package.json is present and has some pre-defined npm scripts.","params":[{"default":".","description":"The path where package.json of the project is defined.","name":"PATH_CONTEXT","type":"string"},{"default":["version"],"description":"The npm goals you want to run.","name":"ARGS","type":"array"},{"default":"docker.io/library/node:12-alpine@sha256:12048cdfd75d944df35f3144132d9bdeee78015fbd6df765edad1be46599b110","description":"The node image you want to use.","name":"IMAGE","type":"string"}],"steps":[{"args":["$(params.ARGS)"],"command":["npm"],"env":[{"name":"CI","value":"true"}],"image":"$(params.IMAGE)","name":"npm-run","workingDir":"$(workspaces.source.path)/$(params.PATH_CONTEXT)"}],"workspaces":[{"name":"source"}]}}
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: build-tool
  creationTimestamp: 2021-06-18T14:03:04Z
  generation: 3
  labels:
    app.kubernetes.io/version: "0.1"
  managedFields:
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:tekton.dev/pipelines.minVersion: {}
          f:tekton.dev/tags: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        .: {}
        f:description: {}
        f:params: {}
    manager: oc
    operation: Update
    time: 2021-06-22T14:11:34Z
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:steps: {}
        f:workspaces: {}
    manager: Mozilla
    operation: Update
    time: 2021-06-23T12:22:56Z
  name: npm
  namespace: tom-pipeline-from-scratch
  resourceVersion: "3441902"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/tom-pipeline-from-scratch/tasks/npm
  uid: 40ec4c25-19a4-4cfe-b0a3-63a5d2f240bb
spec:
  description: |-
    This task can be used to run npm goals on a project.
    This task can be used to run npm goals on a project where package.json is present and has some pre-defined npm scripts.
  params:
  - default: .
    description: The path where package.json of the project is defined.
    name: PATH_CONTEXT
    type: string
  - default:
    - version
    description: The npm goals you want to run.
    name: ARGS
    type: array
  - default: docker.io/library/node:12-alpine@sha256:12048cdfd75d944df35f3144132d9bdeee78015fbd6df765edad1be46599b110
    description: The node image you want to use.
    name: IMAGE
    type: string
  steps:
  - args:
    - $(params.ARGS)
    command:
    - npm
    env:
    - name: CI
      value: "true"
    image: $(params.IMAGE)
    name: npm-run
    resources: {}
    workingDir: $(workspaces.output.path)/$(params.PATH_CONTEXT)
  workspaces:
  - name: source
